const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const auth = require('../middleware/auth');
router.get('/stats', adminController.getStats);
router.get('/users', adminController.getAllUsers);
router.get('/feedbacks', adminController.getAllFeedbacks);
router.delete('/users/:id', adminController.deleteUser);
router.delete('/feedbacks/:id', adminController.deleteFeedback);
router.get('/stats', adminController.getDashboardStats);
router.get('/recipes', adminController.getAllRecipes);
router.delete('/recipes/:id', adminController.deleteRecipe);
router.put('/:id/premium', adminController.updateUserPremium);
router.put('/users/:id/verify', adminController.toggleVerify);
router.put('/recipes/:id/premium', adminController.toggleRecipePremium);
router.get('/community', adminController.getCommunityPosts);
router.delete('/community/:id', adminController.deleteCommunityPost);
router.get("/history",  adminController.getAllPayments);
router.put('/reset/:id', adminController.resetPass);
router.post('/packages', adminController.createPackage);
router.delete('/packages/:id', adminController.deletePackage);
router.put('/packages/:id', adminController.updatePackage);
router.get('/coupons', adminController.getAllCoupons);
router.post('/coupons', adminController.createCoupon);
router.delete('/coupons/:id', adminController.deleteCoupon);
router.put('/coupons/:id/status', adminController.toggleCouponStatus);
router.put('/coupons/:id', adminController.updateCoupon);
router.post('/send-newsletter',auth, adminController.sendNewsletter);
module.exports = router;