const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const {verifyToken, checkAdmin} = require('../middleware/auth');
router.use(verifyToken, checkAdmin);

router.get('/stats', adminController.getStats);
router.get('/logs', adminController.getActivityLogs);
router.delete('/logs/:id', adminController.deleteActivityLog);
router.get('/users', adminController.getAllUsers);
router.get('/feedbacks', adminController.getAllFeedbacks);
router.delete('/users/:id', adminController.deleteUser);
router.delete('/feedbacks/:id', adminController.deleteFeedback);
router.get('/favorite-stats', adminController.getFavoriteStats);
router.get('/recipes', adminController.getAllRecipes);
router.delete('/recipes/:id', adminController.deleteRecipe);
router.put('/:id/premium', adminController.updateUserPremium);
router.put('/users/:id/verify', adminController.toggleVerify);
router.put('/recipes/:id/premium', adminController.toggleRecipePremium);
router.put('/recipes/:id/classification', adminController.updateRecipeClassification);
router.post('/import-recipes', adminController.importRecipes);
router.get('/community', adminController.getCommunityPosts);
router.delete('/community/:id', adminController.deleteCommunityPost);
router.get('/history', adminController.getAllPayments);
router.put('/history/:orderId/status', adminController.updatePaymentStatus);
router.put('/reset/:id', adminController.resetPass);
router.post('/packages', adminController.createPackage);
router.delete('/packages/:id', adminController.deletePackage);
router.put('/packages/:id', adminController.updatePackage);
router.get('/coupons', adminController.getAllCoupons);
router.post('/coupons', adminController.createCoupon);
router.delete('/coupons/:id', adminController.deleteCoupon);
router.put('/coupons/:id/status', adminController.toggleCouponStatus);
router.put('/coupons/:id', adminController.updateCoupon);
router.post('/send-newsletter', adminController.sendNewsletter);
router.get('/user-reports', adminController.getUserReports);
router.put('/user-reports/:id/status', adminController.updateUserReportStatus);
router.delete('/user-reports/:id', adminController.deleteUserReport);

router.get('/recipe-reports', adminController.getRecipeReports);
router.put('/recipe-reports/:id/status', adminController.updateRecipeReportStatus);
router.delete('/recipe-reports/:id', adminController.deleteRecipeReport);

module.exports = router;